name: test ci

on:
  workflow_dispatch:

jobs:
  create-ro-token:
    runs-on: ubuntu-latest
    outputs:
      cds_ro_token: ${{ steps.ro-token.outputs.token }}
    steps:
      - name: Get token from github app
        id: github-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ vars.RO_APP_ID }}
          private_key: ${{ secrets.RO_APP_KEY }}
      - name: Set output
        id: ro-token
        run: |
          echo "::set-output name=token::${{ steps.github-app.outputs.token}}"

  test-checkout-current-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get token from github app
        id: github-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ vars.RO_APP_ID }}
          private_key: ${{ secrets.RO_APP_KEY }}
          
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.github-app.outputs.token }}
      
  test-checkout-public-repo:
    needs: create-ro-token
    uses: matt-lewis-testing-org/ro-test/.github/workflows/ci.yml@main
    with:
      token: ${{ steps.create-ro-token.outputs.cds_ro_token }}
