name: test ci

on:
  workflow_dispatch:

jobs:
  create-ro-token:
    runs-on: ubuntu-latest
    # outputs:
    #   ro_token: ${{ steps.token-ro.outputs.cds_ro_token }}
    steps:
      - name: Get token from github app
        id: github-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.RO_APP_ID }}
          private-key: ${{ secrets.RO_APP_KEY }}
          owner: ${{ github.repository_owner }}
      # - name: Set output
      #   id: token-ro
      #   run: |
      #     echo "cds_ro_token=${{ steps.github-app.outputs.token }}" >> "$GITHUB_OUTPUT"
      # - name: Set output
      #   id: ro-token
      #   run: |
      #     # echo "cds_ro_token=${{ steps.github-app.outputs.token }}" >> "$GITHUB_ENV"
      #     echo "GITHUB_TOKEN=${{ steps.github-app.outputs.token }}" >> "$GITHUB_ENV"
      - name: test gh token with cli
        run: |
          gh repo list matt-lewis-testing-org
        env:
          GITHUB_TOKEN: ${{ steps.github-app.outputs.token }}

  test-checkout-current-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get token from github app
        id: github-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ vars.RO_APP_ID }}
          private_key: ${{ secrets.RO_APP_KEY }}
          
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.github-app.outputs.token }}
  
  test-output-call:
    runs-on: ubuntu-latest
    needs: [create-ro-token]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ needs.create-ro-token.outputs.ro_token }}
          
      
  # test-checkout-public-repo:
  #   needs: create-ro-token
  #   uses: matt-lewis-testing-org/ro-test/.github/workflows/ci.yml@main
  #   with:
  #     token: ${{ needs.create-ro-token.env.cds_ro_token }}
