name: test ci

on:
  workflow_dispatch:

jobs:
  create-ro-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get token from github app
        id: github-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ vars.RO_APP_ID }}
          private_key: ${{ secrets.RO_APP_KEY }}
      - name: Set output
        id: ro-token
        run: |
          echo "cds_ro_token=${{ steps.github-app.outputs.token }}" >> "$GITHUB_ENV"

  test-checkout-current-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get token from github app
        id: github-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ vars.RO_APP_ID }}
          private_key: ${{ secrets.RO_APP_KEY }}
          
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.github-app.outputs.token }}
      
  test-checkout-public-repo:
    runs-on: ubuntu-latest
    needs: create-ro-token
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: matt-lewis-testing-org/reusable-actions
          path: ./reusable-actions
          token: ${{ env.cds_ro_token }}
          ref: main
