name: example ci

on:
  workflow_call:
    inputs:
      token:
        description: |
          token used for RO privlages
        type: string
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ inputs.token }}
